// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MyInterface is an autogenerated mock type for the MyInterface type
type MyInterface struct {
	mock.Mock
}

type MyInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MyInterface) EXPECT() *MyInterface_Expecter {
	return &MyInterface_Expecter{mock: &_m.Mock}
}

// MyMethod provides a mock function with given fields:
func (_m *MyInterface) MyMethod() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MyMethod")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MyInterface_MyMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyMethod'
type MyInterface_MyMethod_Call struct {
	*mock.Call
}

// MyMethod is a helper method to define mock.On call
func (_e *MyInterface_Expecter) MyMethod() *MyInterface_MyMethod_Call {
	return &MyInterface_MyMethod_Call{Call: _e.mock.On("MyMethod")}
}

func (_c *MyInterface_MyMethod_Call) Run(run func()) *MyInterface_MyMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MyInterface_MyMethod_Call) Return(_a0 int) *MyInterface_MyMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MyInterface_MyMethod_Call) RunAndReturn(run func() int) *MyInterface_MyMethod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMyInterface creates a new instance of MyInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMyInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MyInterface {
	mock := &MyInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
