// Code generated by mockery v2.38.0. DO NOT EDIT.

package mypackage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMyInterface is an autogenerated mock type for the MyInterface type
type MockMyInterface[T interface{}] struct {
	mock.Mock
}

type MockMyInterface_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockMyInterface[T]) EXPECT() *MockMyInterface_Expecter[T] {
	return &MockMyInterface_Expecter[T]{mock: &_m.Mock}
}

// MyMethod provides a mock function with given fields: _a0, _a1
func (_m *MockMyInterface[T]) MyMethod(_a0 context.Context, _a1 T) (int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MyMethod")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMyInterface_MyMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyMethod'
type MockMyInterface_MyMethod_Call[T interface{}] struct {
	*mock.Call
}

// MyMethod is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 T
func (_e *MockMyInterface_Expecter[T]) MyMethod(_a0 interface{}, _a1 interface{}) *MockMyInterface_MyMethod_Call[T] {
	return &MockMyInterface_MyMethod_Call[T]{Call: _e.mock.On("MyMethod", _a0, _a1)}
}

func (_c *MockMyInterface_MyMethod_Call[T]) Run(run func(_a0 context.Context, _a1 T)) *MockMyInterface_MyMethod_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockMyInterface_MyMethod_Call[T]) Return(_a0 int, _a1 error) *MockMyInterface_MyMethod_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMyInterface_MyMethod_Call[T]) RunAndReturn(run func(context.Context, T) (int, error)) *MockMyInterface_MyMethod_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockMyInterface creates a new instance of MockMyInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMyInterface[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMyInterface[T] {
	mock := &MockMyInterface[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
